server:
    port: 8083

spring:
    application:
        name: enrollment-service
    
    datasource:
        url: jdbc:postgresql://localhost:5433/enrollment_db
        username: enrollment_user
        password: enrollment_password
        driver-class-name: org.postgresql.Driver
    
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                "[format_sql]": true
            
    rabbitmq:
        host: localhost
        port: 5672
        username: rabbit_user
        password: rabbit_password
    
    data:
        redis:
            host: localhost
            port: 6379
            password: redis_password

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics