server:
    port: 8081

spring:
    application:
        name: auth-service
    
    datasource:
        url: jdbc:postgresql://localhost:5431/auth_db
        username: auth_user
        password: auth_password
        driver-class-name: org.postgresql.Driver
    
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                "[format_sql]": true

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8081

    data:
        redis:
            host: localhost
            port: 6379
            password: redis_password

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics