server:
    port: 8084

spring:
    application:
        name: grading-service

    datasource:
        url: jdbc:postgresql://localhost:5434/grading_db
        username: grading_user
        password: grading_password
        driver-class-name: org.postgresql.Driver
    
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                "[format_sql]": true

    rabbitmq:
        host: localhost
        port: 5672
        username: rabbit_user
        password: rabbit_password
    
    data:
        redis:
            host: localhost
            port: 6379
            password: redis_password

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8081
                    jwk-set-uri: http://localhost:8081/.well-known/jwks.json

logging:
    level:
        "[org.springframework.security]": DEBUG
        "[org.springframework.security.oauth2]": DEBUG

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics

resilience4j:
    circuitbreaker:
        instances:
            gradeService:
                registerHealthIndicator: true
                slidingWindowSize: 10
                minimumNumberOfCalls: 5
                permittedNumberOfCallsInHalfOpenState: 3
                automaticTransitionFromOpenToHalfOpenEnabled: true
                waitDurationInOpenState: 5s
                failureRateThreshold: 50
                eventConsumerBufferSize: 10
    retry:
        instances:
            gradeService:
                maxAttempts: 3
                waitDuration: 1s
                enableExponentialBackoff: true
                exponentialBackoffMultiplier: 2